spring:
  cloud:
    gateway:
      routes:
        # Auth Service - /api/auth/** (strip /api prefix)
        - id: auth-service-api
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
        
        # Auth Service - direct access (for service-to-service)
        - id: auth-service-direct
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1
        
        # Patient Service - /api/patients/** (strip /api prefix)
        - id: patient-service-api
          uri: lb://patient-service
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
        
        # Patient Service - direct access
        - id: patient-service-direct
          uri: lb://patient-service
          predicates:
            - Path=/patient-service/**
          filters:
            - StripPrefix=1
        
        # Medicine Service - /api/medicines/** (strip /api prefix)
        - id: medicine-service-medicines-api
          uri: lb://medicine-service
          predicates:
            - Path=/api/medicines/**
          filters:
            - StripPrefix=1
        
        # Medicine Service - direct access
        - id: medicine-service-direct
          uri: lb://medicine-service
          predicates:
            - Path=/medicine-service/**
          filters:
            - StripPrefix=1
        
        # HR Service - /api/hr/** (strip /api prefix)
        - id: hr-service-api
          uri: lb://hr-service
          predicates:
            - Path=/api/hr/**
          filters:
            - StripPrefix=1
        
        # HR Service - direct access
        - id: hr-service-direct
          uri: lb://hr-service
          predicates:
            - Path=/hr-service/**
          filters:
            - StripPrefix=1
        
        # Appointment Service - /api/appointments/** (strip /api prefix)
        - id: appointment-service-api
          uri: lb://appointment-service
          predicates:
            - Path=/api/appointments/**
          filters:
            - StripPrefix=1
        
        # Appointment Service - direct access
        - id: appointment-service-direct
          uri: lb://appointment-service
          predicates:
            - Path=/appointment-service/**
          filters:
            - StripPrefix=1
        
        # Medical Exam Service - /api/exams/** (strip /api prefix)
        - id: medical-exam-service-exams-api
          uri: lb://medical-exam-service
          predicates:
            - Path=/api/exams/**
          filters:
            - StripPrefix=1
        
        # Medical Exam Service - /api/prescriptions/** (strip /api prefix)
        - id: medical-exam-service-prescriptions-api
          uri: lb://medical-exam-service
          predicates:
            - Path=/api/prescriptions/**
          filters:
            - StripPrefix=1
        
        # Medical Exam Service - direct access
        - id: medical-exam-service-direct
          uri: lb://medical-exam-service
          predicates:
            - Path=/medical-exam-service/**
          filters:
            - StripPrefix=1
        
        # Billing Service - /api/invoices/** (strip /api prefix)
        - id: billing-service-invoices-api
          uri: lb://billing-service
          predicates:
            - Path=/api/invoices/**
          filters:
            - StripPrefix=1
        
        # Billing Service - /api/payments/** (strip /api prefix)
        - id: billing-service-payments-api
          uri: lb://billing-service
          predicates:
            - Path=/api/payments/**
          filters:
            - StripPrefix=1
        
        # Billing Service - direct access
        - id: billing-service-direct
          uri: lb://billing-service
          predicates:
            - Path=/billing-service/**
          filters:
            - StripPrefix=1
        
        # Report Service - /api/reports/** (strip /api prefix)
        - id: report-service-api
          uri: lb://report-service
          predicates:
            - Path=/api/reports/**
          filters:
            - StripPrefix=1
        
        # Report Service - direct access
        - id: report-service-direct
          uri: lb://report-service
          predicates:
            - Path=/report-service/**
          filters:
            - StripPrefix=1
        
        # Notification Service - /api/notifications/** (strip /api prefix)
        - id: notification-service-api
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - StripPrefix=1
        
        # Notification Service - direct access
        - id: notification-service-direct
          uri: lb://notification-service
          predicates:
            - Path=/notification-service/**
          filters:
            - StripPrefix=1

jwt:
  public-key: ${JWT_PUBLIC_KEY:-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAs/yJcHARVAGn1xzVbndvyuj1spOinx4IXLP+r73zRpd9Aqjq8gKDnJolEPHXM55wdLxkvjXMEv3p665tbcRXUyHUWI6/p/UIeB6pEZyNUqUj6BiiE0lhv3nINmlAXeXibigMaOzUXBAIl7fuw29oG5bCWjjoUBWgVMFRkGAJfOBZDnqG1OgX1ibjCP4qDI5RgBuv32xAP3/n3eUmNel3+kxAj/ETVkmRbJfiJh61qc4n3bUxXXpJkPnAdGyNxcVPXArASLkKDlb1PSQOJ1x83s75yvXgLMxzt1hgThArM4vlFZRx8IjTbWIpJAjAqil0PLRIX6L3FzoRW6xuHRmMGwIDAQAB-----END PUBLIC KEY-----}

server:
  port: ${API_GATEWAY_PORT:8080}

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVICE_HOST:localhost}:${DISCOVERY_SERVICE_PORT:8761}/eureka/
