spring:
  cloud:
    gateway:
      routes:
        # Auth Service - /api/auth/** (forward as-is)
        - id: auth-service-api
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        
        # Auth Service - direct access (for service-to-service)
        - id: auth-service-direct
          uri: lb://auth-service
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1
        
        # Patient Service - /api/patients/** (forward as-is)
        - id: patient-service-api
          uri: lb://patient-service
          predicates:
            - Path=/api/patients/**
        
        # Patient Service - direct access
        - id: patient-service-direct
          uri: lb://patient-service
          predicates:
            - Path=/patient-service/**
          filters:
            - StripPrefix=1
        
        # Medicine Service - /api/medicines/** (forward as-is)
        - id: medicine-service-medicines-api
          uri: lb://medicine-service
          predicates:
            - Path=/api/medicines/**
        
        # Medicine Service - /api/medicines/categories/** (forward as-is)
        - id: medicine-service-categories-api
          uri: lb://medicine-service
          predicates:
            - Path=/api/medicines/categories/**
        
        # Medicine Service - direct access
        - id: medicine-service-direct
          uri: lb://medicine-service
          predicates:
            - Path=/medicine-service/**
          filters:
            - StripPrefix=1
        
        # HR Service - /api/hr/** (forward as-is)
        - id: hr-service-api
          uri: lb://hr-service
          predicates:
            - Path=/api/hr/**
        
        # HR Service - direct access
        - id: hr-service-direct
          uri: lb://hr-service
          predicates:
            - Path=/hr-service/**
          filters:
            - StripPrefix=1
        
        # Appointment Service - /api/appointments/** (forward as-is)
        - id: appointment-service-api
          uri: lb://appointment-service
          predicates:
            - Path=/api/appointments/**
        
        # Appointment Service - direct access
        - id: appointment-service-direct
          uri: lb://appointment-service
          predicates:
            - Path=/appointment-service/**
          filters:
            - StripPrefix=1
        
        # Medical Exam Service - /api/exams/** (forward as-is)
        - id: medical-exam-service-exams-api
          uri: lb://medical-exam-service
          predicates:
            - Path=/api/exams/**
        
        # Medical Exam Service - /api/prescriptions/** (forward as-is)
        - id: medical-exam-service-prescriptions-api
          uri: lb://medical-exam-service
          predicates:
            - Path=/api/prescriptions/**
        
        # Medical Exam Service - direct access
        - id: medical-exam-service-direct
          uri: lb://medical-exam-service
          predicates:
            - Path=/medical-exam-service/**
          filters:
            - StripPrefix=1

jwt:
  public-key: ${JWT_PUBLIC_KEY:-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAs/yJcHARVAGn1xzVbndvyuj1spOinx4IXLP+r73zRpd9Aqjq8gKDnJolEPHXM55wdLxkvjXMEv3p665tbcRXUyHUWI6/p/UIeB6pEZyNUqUj6BiiE0lhv3nINmlAXeXibigMaOzUXBAIl7fuw29oG5bCWjjoUBWgVMFRkGAJfOBZDnqG1OgX1ibjCP4qDI5RgBuv32xAP3/n3eUmNel3+kxAj/ETVkmRbJfiJh61qc4n3bUxXXpJkPnAdGyNxcVPXArASLkKDlb1PSQOJ1x83s75yvXgLMxzt1hgThArM4vlFZRx8IjTbWIpJAjAqil0PLRIX6L3FzoRW6xuHRmMGwIDAQAB-----END PUBLIC KEY-----}

server:
  port: ${API_GATEWAY_PORT:8080}

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVICE_HOST:localhost}:${DISCOVERY_SERVICE_PORT:8761}/eureka/
