spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: medicine-service
              uri: lb://medicine-service
              predicates:
                - Path=/medicine-service/**

server:
  port: ${API_GATEWAY_PORT:8080}

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVICE_HOST:localhost}:${DISCOVERY_SERVICE_PORT:8761}/eureka/
