spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: medicine-service
              uri: lb://medicine-service
              predicates:
                - Path=/medicine-service/**
              filters:
                - StripPrefix=1
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/auth-service/**
              filters:
                - StripPrefix=1
            - id: hr-service
              uri: lb://hr-service
              predicates:
                - Path=/hr-service/**
              filters:
                - StripPrefix=1
            - id: patient-service
              uri: lb://patient-service
              predicates:
                - Path=/patient-service/**
              filters:
                - StripPrefix=1
            - id: appointment-service
              uri: lb://appointment-service
              predicates:
                - Path=/appointment-service/**
              filters:
                - StripPrefix=1
            - id: medical-exam-service
              uri: lb://medical-exam-service
              predicates:
                - Path=/medical-exam-service/**
              filters:
                - StripPrefix=1

jwt:
  public-key: ${JWT_PUBLIC_KEY:-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAs/yJcHARVAGn1xzVbndvyuj1spOinx4IXLP+r73zRpd9Aqjq8gKDnJolEPHXM55wdLxkvjXMEv3p665tbcRXUyHUWI6/p/UIeB6pEZyNUqUj6BiiE0lhv3nINmlAXeXibigMaOzUXBAIl7fuw29oG5bCWjjoUBWgVMFRkGAJfOBZDnqG1OgX1ibjCP4qDI5RgBuv32xAP3/n3eUmNel3+kxAj/ETVkmRbJfiJh61qc4n3bUxXXpJkPnAdGyNxcVPXArASLkKDlb1PSQOJ1x83s75yvXgLMxzt1hgThArM4vlFZRx8IjTbWIpJAjAqil0PLRIX6L3FzoRW6xuHRmMGwIDAQAB-----END PUBLIC KEY-----}

server:
  port: ${API_GATEWAY_PORT:8080}

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVICE_HOST:localhost}:${DISCOVERY_SERVICE_PORT:8761}/eureka/
