spring:
  docker:
    compose:
      enabled: ${DOCKER_COMPOSE_ENABLED:false}
      file: ${DOCKER_COMPOSE_FILE_AUTH_SERVICE:file:infrastructure/dev/auth-service/compose.yaml}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${AUTH_DB_HOST:localhost}:${AUTH_DB_PORT:3306}/${AUTH_DB_NAME:mydatabase}
    username: ${AUTH_DB_USERNAME:myuser}
    password: ${AUTH_DB_PASSWORD:secret}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  private-key: ${JWT_PRIVATE_KEY:-----BEGIN PRIVATE KEY-----MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCz/IlwcBFUAafXHNVud2/K6PWyk6KfHghcs/6vvfNGl30CqOryAoOcmiUQ8dcznnB0vGS+NcwS/enrrm1txFdTIdRYjr+n9Qh4HqkRnI1SpSPoGKITSWG/ecg2aUBd5eJuKAxo7NRcEAiXt+7Db2gblsJaOOhQFaBUwVGQYAl84FkOeobU6BfWJuMI/ioMjlGAG6/fbEA/f+fd5SY16Xf6TECP8RNWSZFsl+ImHrWpzifdtTFdekmQ+cB0bI3FxU9cCsBIuQoOVvU9JA4nXHzezvnK9eAszHO3WGBOECszi+UVlHHwiNNtYikkCMCqKXQ8tEhfovcXOhFbrG4dGYwbAgMBAAECggEARy9aLF4mfFMrTqjYwRf73wTEKBy79LKsG/4UfO1jikff6W1lftH/u7A7eLgtpPzE/WaFcbVVQS2rlssl/IPrBbYbhervYj5HWzrFI3IHcuhdiy4y6+3Z+yDvTpXSH1EMfQTZ46XHV6H/xAG7LRCi3EaEF6rqNsJW5y6OU8un9PsbLs/Gmpi25f983qZsoDdXfHL3xEF/ESzYiCf1x9Gnm9rRNJx8NgrxjLlJxzfAToKlPsY4M6vYaL/Rqyyp1hAFRVYN5ZC2ju75yAKqhR+2u4aoTE2NPDZJNFn4HvwIcb7FzCjKQn3qgCCOyYbfCnt0E6ICbsTYP/6yvoidRxB6AQKBgQDyfZG3F3IOMEoO0eoIh9MdUQ85nfhhbCzyYJy/3dMf98ADrFcS8x7OaJxjzpfIOB4m2ELCbysfBOIil6wlhrzUDoxsSwl+cfxUE8nYVEC6YTAxGQpCKUrPlSCnFjOwN34+AZpSrWy0R6DztpLFoNnCRNcD9rQOHfOZ/hw0gPAJjQKBgQC+A4bw0qSj5IkMLJ3RLSV6d6MEkIgQk64ziy8i3qagQHgyn4QHKE+qIUSYQMGjbTvRmY+ZV4OC1nDMNoatwAq9dk9c4jQCIfz+K0ik/0EYL+XbeH/ogUJgtcgI7qegdVhS5qNNnCev6tw93H8PuWe6qymIgscEvP/NW7aCJYH+RwKBgH1xZiMwVsluQ7F8+DPnh9gfqd+lj+teGbZdMlmzOFfOQ5/i1Lyx1pry1QxwwGZMWZTAxXBuMAGA9jbs/ZoAJMkSqaQQAV5POziHcCCgHUgNpO+RQ5RMZi4SuGyXeK/NVVpgW+QvYQ+2ClZpeW4RMvVjxVOAmU7AQdfE8/RZS1O1AoGARdwIHbxkObmJRYeV0lUV5Wvc7I2y6N1S+7JddyWC/4IUbxBEu1jvyS4ICS4tw0ci6hHaQNdzC4SJ3hrh8zma+UNpNE4aLvqOCGijgb4zEZByovkvla0IWYQb8mTEDnN2MKyJN7yEvuHLbZcGxCI3Z+MMFxt1zmEqbzcb58egfnsCgYEA1dBSsNNJJVSuj+HcrxCKRb1BmgIpD4Mbr7M/sp4OZQ5jDqBOjyWdBHnZfpzMVLbqgWwunsDTjA0tFYqziunpI/MmzTfsy5oPEu05GeIQ8X+8Aqw7RCBP+dv8T8Wur+eMWS9wDcObV3nLaBad6G+DIZJwaPdoZJpQ2NQruQbGOm0=-----END PRIVATE KEY-----}
  public-key: ${JWT_PUBLIC_KEY:-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAs/yJcHARVAGn1xzVbndvyuj1spOinx4IXLP+r73zRpd9Aqjq8gKDnJolEPHXM55wdLxkvjXMEv3p665tbcRXUyHUWI6/p/UIeB6pEZyNUqUj6BiiE0lhv3nINmlAXeXibigMaOzUXBAIl7fuw29oG5bCWjjoUBWgVMFRkGAJfOBZDnqG1OgX1ibjCP4qDI5RgBuv32xAP3/n3eUmNel3+kxAj/ETVkmRbJfiJh61qc4n3bUxXXpJkPnAdGyNxcVPXArASLkKDlb1PSQOJ1x83s75yvXgLMxzt1hgThArM4vlFZRx8IjTbWIpJAjAqil0PLRIX6L3FzoRW6xuHRmMGwIDAQAB-----END PUBLIC KEY-----}
  refresh-token:
    expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800}
  access-token:
    expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:3600}

server:
  port: ${AUTH_SERVICE_PORT:8082}

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVICE_HOST:localhost}:${DISCOVERY_SERVICE_PORT:8761}/eureka/
