spring:
  docker:
    compose:
      enabled: ${DOCKER_COMPOSE_ENABLED:false}
      file: ${DOCKER_COMPOSE_FILE_HR_SERVICE:file:infrastructure/dev/hr-service/compose.yaml}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${HR_DB_HOST:localhost}:${HR_DB_PORT:3306}/${HR_DB_NAME:mydatabase}
    username: ${HR_DB_USERNAME:myuser}
    password: ${HR_DB_PASSWORD:secret}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: ${HR_SERVICE_PORT:8084}

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVICE_HOST:localhost}:${DISCOVERY_SERVICE_PORT:8761}/eureka/

# Feign client configuration for direct service URLs
# Uses service discovery (Eureka) by default when URL is empty
# For explicit URL: set APPOINTMENT_SERVICE_URL env var in compose.yaml
feign:
  client:
    config:
      appointment-service:
        url: ${APPOINTMENT_SERVICE_URL:http://appointment-service-pro:8085}
