spring:
  docker:
    compose:
      enabled: ${DOCKER_COMPOSE_ENABLED:false}
      file: ${DOCKER_COMPOSE_FILE_MEDICAL_EXAM_SERVICE:file:infrastructure/dev/medical-exam-service/compose.yaml}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MEDICAL_EXAM_DB_HOST:localhost}:${MEDICAL_EXAM_DB_PORT:3310}/${MEDICAL_EXAM_DB_NAME:medical_exam_db}
    username: ${MEDICAL_EXAM_DB_USERNAME:myuser}
    password: ${MEDICAL_EXAM_DB_PASSWORD:secret}
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: ${MEDICAL_EXAM_SERVICE_PORT:8086}

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVICE_HOST:localhost}:${DISCOVERY_SERVICE_PORT:8761}/eureka/

# Medicine service integration
medicine-service:
  base-url: http://${MEDICINE_SERVICE_HOST:localhost}:${MEDICINE_SERVICE_PORT:8082}

# Appointment service integration (for fetching appointment data during exam creation)
appointment-service:
  base-url: http://${APPOINTMENT_SERVICE_HOST:appointment-service-pro}:${APPOINTMENT_SERVICE_PORT:8085}
