package com.hms.auth_service.mappers;

import com.hms.auth_service.entities.Account;
import com.hms.common.dtos.account.AccountRequest;
import com.hms.common.dtos.account.AccountResponse;
import com.hms.common.enums.RoleEnum;
import com.hms.common.test.TestDataFactory;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Unit tests for AccountMapper.
 * Tests MapStruct mapper methods for correct field mapping.
 * 
 * Note: MapStruct mappers are generated at compile time and need Spring context
 * for dependency injection when using componentModel = "spring".
 */
@SpringBootTest(properties = {
    "spring.cloud.config.enabled=false",
    "eureka.client.enabled=false",
    "spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL",
    "spring.datasource.driver-class-name=org.h2.Driver",
    "spring.jpa.hibernate.ddl-auto=create-drop"
})
@ActiveProfiles("test")
@DisplayName("UC-AUTH-010/011: AccountMapper Unit Tests")
class AccountMapperTest {

    @Autowired
    private AccountMapper mapper;

    private Account testEntity;
    private AccountRequest testRequest;

    @BeforeEach
    void setUp() {
        // Setup test entity
        testEntity = new Account();
        testEntity.setId(TestDataFactory.uuid());
        testEntity.setEmail(TestDataFactory.uniqueEmail());
        testEntity.setPassword("hashedPassword");
        testEntity.setRole(RoleEnum.PATIENT);
        testEntity.setEmailVerified(true);

        // Setup test request
        testRequest = new AccountRequest();
        testRequest.setEmail(TestDataFactory.uniqueEmail());
        testRequest.setPassword(TestDataFactory.simplePassword());
    }

    @Nested
    @DisplayName("Entity to Response Mapping")
    class EntityToResponseTests {

        @Test
        @DisplayName("UC-AUTH-010: Should map entity to response correctly")
        void entityToResponse_shouldMapAllFields() {
            // When
            AccountResponse response = mapper.entityToResponse(testEntity);

            // Then
            assertThat(response).isNotNull();
            assertThat(response.getId()).isEqualTo(testEntity.getId());
            assertThat(response.getEmail()).isEqualTo(testEntity.getEmail());
            // Password should NOT be mapped to response (security)
        }

        @Test
        @DisplayName("Should handle null entity gracefully")
        void entityToResponse_withNullEntity_shouldReturnNull() {
            // When
            AccountResponse response = mapper.entityToResponse(null);

            // Then
            assertThat(response).isNull();
        }

        @Test
        @DisplayName("Should map role correctly")
        void entityToResponse_shouldMapRole() {
            // Given
            testEntity.setRole(RoleEnum.DOCTOR);

            // When
            AccountResponse response = mapper.entityToResponse(testEntity);

            // Then
            assertThat(response.getRole()).isEqualTo(RoleEnum.DOCTOR);
        }
    }

    @Nested
    @DisplayName("Request to Entity Mapping")
    class RequestToEntityTests {

        @Test
        @DisplayName("UC-AUTH-011: Should map request to entity correctly")
        void requestToEntity_shouldMapAllFields() {
            // When
            Account entity = mapper.requestToEntity(testRequest);

            // Then
            assertThat(entity).isNotNull();
            assertThat(entity.getEmail()).isEqualTo(testRequest.getEmail());
            assertThat(entity.getPassword()).isEqualTo(testRequest.getPassword());
            // ID should be null (generated by DB)
            assertThat(entity.getId()).isNull();
        }

        @Test
        @DisplayName("Should handle null request gracefully")
        void requestToEntity_withNullRequest_shouldReturnNull() {
            // When
            Account entity = mapper.requestToEntity(null);

            // Then
            assertThat(entity).isNull();
        }
    }

    @Nested
    @DisplayName("Partial Update Mapping")
    class PartialUpdateTests {

        @Test
        @DisplayName("Should update entity fields from request")
        void partialUpdate_shouldModifyEntity() {
            // Given
            Account existingEntity = new Account();
            existingEntity.setId(TestDataFactory.uuid());
            existingEntity.setEmail("old@email.com");
            existingEntity.setPassword("oldPassword");
            existingEntity.setRole(RoleEnum.PATIENT);

            AccountRequest updateRequest = new AccountRequest();
            updateRequest.setEmail("new@email.com");
            updateRequest.setPassword("newPassword");

            // When
            mapper.partialUpdate(updateRequest, existingEntity);

            // Then
            assertThat(existingEntity.getEmail()).isEqualTo("new@email.com");
            assertThat(existingEntity.getPassword()).isEqualTo("newPassword");
            // ID should remain unchanged
            assertThat(existingEntity.getId()).isNotNull();
        }

        @Test
        @DisplayName("Should not throw when updating with null request")
        void partialUpdate_withNullRequest_shouldNotThrow() {
            // Given
            Account existingEntity = new Account();
            existingEntity.setEmail("old@email.com");

            // When & Then - should not throw
            mapper.partialUpdate(null, existingEntity);
            
            // Entity should remain unchanged
            assertThat(existingEntity.getEmail()).isEqualTo("old@email.com");
        }
    }
}
