package com.hms.medicine_service.mappers;

import com.hms.medicine_service.dtos.category.CategoryRequest;
import com.hms.medicine_service.dtos.category.CategoryResponse;
import com.hms.medicine_service.entities.Category;
import com.hms.common.test.TestDataFactory;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import java.time.Instant;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Unit tests for CategoryMapper.
 * Tests MapStruct mapper methods for correct field mapping.
 * 
 * Note: MapStruct mappers are generated at compile time and need Spring context
 * for dependency injection when using componentModel = "spring".
 */
@SpringBootTest(properties = {
    "spring.cloud.config.enabled=false",
    "eureka.client.enabled=false",
    "spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL",
    "spring.datasource.driver-class-name=org.h2.Driver",
    "spring.jpa.hibernate.ddl-auto=create-drop"
})
@ActiveProfiles("test")
@DisplayName("UC-MED-003: CategoryMapper Unit Tests")
class CategoryMapperTest {

    @Autowired
    private CategoryMapper mapper;

    private Category testEntity;
    private CategoryRequest testRequest;

    @BeforeEach
    void setUp() {
        // Setup test entity
        testEntity = new Category();
        testEntity.setId(TestDataFactory.uuid());
        testEntity.setName("Antibiotics");
        testEntity.setDescription("Antibiotic medications for bacterial infections");
        testEntity.setCreatedAt(Instant.now());
        testEntity.setUpdatedAt(Instant.now());
        testEntity.setCreatedBy("admin");
        testEntity.setUpdatedBy("admin");

        // Setup test request
        testRequest = new CategoryRequest();
        testRequest.setName("Pain Relievers");
        testRequest.setDescription("Medications for pain management");
    }

    @Nested
    @DisplayName("Entity to Response Mapping")
    class EntityToResponseTests {

        @Test
        @DisplayName("UC-MED-003: Should map entity to response correctly")
        void entityToResponse_shouldMapAllFields() {
            // When
            CategoryResponse response = mapper.entityToResponse(testEntity);

            // Then
            assertThat(response).isNotNull();
            assertThat(response.getId()).isEqualTo(testEntity.getId());
            assertThat(response.getName()).isEqualTo(testEntity.getName());
            assertThat(response.getDescription()).isEqualTo(testEntity.getDescription());
            assertThat(response.getCreatedAt()).isEqualTo(testEntity.getCreatedAt());
            assertThat(response.getUpdatedAt()).isEqualTo(testEntity.getUpdatedAt());
            assertThat(response.getCreatedBy()).isEqualTo(testEntity.getCreatedBy());
            assertThat(response.getUpdatedBy()).isEqualTo(testEntity.getUpdatedBy());
        }

        @Test
        @DisplayName("Should handle null entity gracefully")
        void entityToResponse_withNullEntity_shouldReturnNull() {
            // When
            CategoryResponse response = mapper.entityToResponse(null);

            // Then
            assertThat(response).isNull();
        }

        @Test
        @DisplayName("Should handle entity with null optional fields")
        void entityToResponse_withNullOptionalFields_shouldMapOnlyRequiredFields() {
            // Given
            testEntity.setDescription(null);
            testEntity.setCreatedBy(null);
            testEntity.setUpdatedBy(null);

            // When
            CategoryResponse response = mapper.entityToResponse(testEntity);

            // Then
            assertThat(response).isNotNull();
            assertThat(response.getId()).isEqualTo(testEntity.getId());
            assertThat(response.getName()).isEqualTo(testEntity.getName());
            assertThat(response.getDescription()).isNull();
            assertThat(response.getCreatedBy()).isNull();
            assertThat(response.getUpdatedBy()).isNull();
        }
    }

    @Nested
    @DisplayName("Request to Entity Mapping")
    class RequestToEntityTests {

        @Test
        @DisplayName("Should map request to entity correctly")
        void requestToEntity_shouldMapAllFields() {
            // When
            Category entity = mapper.requestToEntity(testRequest);

            // Then
            assertThat(entity).isNotNull();
            assertThat(entity.getName()).isEqualTo(testRequest.getName());
            assertThat(entity.getDescription()).isEqualTo(testRequest.getDescription());
            // ID should be null (generated by DB)
            assertThat(entity.getId()).isNull();
            // Audit fields should be null (set by JPA auditing)
            assertThat(entity.getCreatedAt()).isNull();
            assertThat(entity.getUpdatedAt()).isNull();
        }

        @Test
        @DisplayName("Should handle null request gracefully")
        void requestToEntity_withNullRequest_shouldReturnNull() {
            // When
            Category entity = mapper.requestToEntity(null);

            // Then
            assertThat(entity).isNull();
        }

        @Test
        @DisplayName("Should handle request with null description")
        void requestToEntity_withNullDescription_shouldMapOnlyName() {
            // Given
            testRequest.setDescription(null);

            // When
            Category entity = mapper.requestToEntity(testRequest);

            // Then
            assertThat(entity).isNotNull();
            assertThat(entity.getName()).isEqualTo(testRequest.getName());
            assertThat(entity.getDescription()).isNull();
        }
    }

    @Nested
    @DisplayName("Partial Update Mapping")
    class PartialUpdateTests {

        @Test
        @DisplayName("Should update entity fields from request")
        void partialUpdate_shouldModifyEntity() {
            // Given
            Category existingEntity = new Category();
            existingEntity.setId(TestDataFactory.uuid());
            existingEntity.setName("OldCategory");
            existingEntity.setDescription("Old description");

            CategoryRequest updateRequest = new CategoryRequest();
            updateRequest.setName("UpdatedCategory");
            updateRequest.setDescription("Updated description");

            // When
            mapper.partialUpdate(updateRequest, existingEntity);

            // Then
            assertThat(existingEntity.getName()).isEqualTo(updateRequest.getName());
            assertThat(existingEntity.getDescription()).isEqualTo(updateRequest.getDescription());
            // ID should remain unchanged
            assertThat(existingEntity.getId()).isNotNull();
        }

        @Test
        @DisplayName("Should preserve ID during partial update")
        void partialUpdate_shouldPreserveId() {
            // Given
            String originalId = TestDataFactory.uuid();
            Category existingEntity = new Category();
            existingEntity.setId(originalId);
            existingEntity.setName("Original");

            CategoryRequest updateRequest = new CategoryRequest();
            updateRequest.setName("Updated");
            updateRequest.setDescription("Updated description");

            // When
            mapper.partialUpdate(updateRequest, existingEntity);

            // Then
            assertThat(existingEntity.getId()).isEqualTo(originalId);
        }

        @Test
        @DisplayName("Should preserve audit fields during partial update")
        void partialUpdate_shouldPreserveAuditFields() {
            // Given
            Category existingEntity = new Category();
            existingEntity.setId(TestDataFactory.uuid());
            existingEntity.setName("Original");
            Instant originalCreatedAt = Instant.now().minusSeconds(3600);
            String originalCreatedBy = "admin";
            existingEntity.setCreatedAt(originalCreatedAt);
            existingEntity.setCreatedBy(originalCreatedBy);

            CategoryRequest updateRequest = new CategoryRequest();
            updateRequest.setName("Updated");
            updateRequest.setDescription("Updated description");

            // When
            mapper.partialUpdate(updateRequest, existingEntity);

            // Then
            assertThat(existingEntity.getCreatedAt()).isEqualTo(originalCreatedAt);
            assertThat(existingEntity.getCreatedBy()).isEqualTo(originalCreatedBy);
        }
    }
}
