services:
  # Database Services
  mysql-auth-service:
    image: mysql:8.0
    container_name: mysql-auth-service
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${AUTH_DB_PASSWORD}
      MYSQL_DATABASE: ${AUTH_DB_NAME}
      MYSQL_USER: ${AUTH_DB_USERNAME}
      MYSQL_PASSWORD: ${AUTH_DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    restart: always
  mysql-hr-service:
    image: mysql:8.0
    container_name: mysql-hr-service
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${HR_DB_PASSWORD}
      MYSQL_DATABASE: ${HR_DB_NAME}
      MYSQL_USER: ${HR_DB_USERNAME}
      MYSQL_PASSWORD: ${HR_DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    restart: always
  mysql-medicine-service:
    image: mysql:8.0
    container_name: mysql-medicine-service
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MEDICINE_DB_PASSWORD}
      MYSQL_DATABASE: ${MEDICINE_DB_NAME}
      MYSQL_USER: ${MEDICINE_DB_USERNAME}
      MYSQL_PASSWORD: ${MEDICINE_DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    restart: always
  mysql-patient-service:
    image: mysql:8.0
    container_name: mysql-patient-service
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${PATIENT_DB_PASSWORD}
      MYSQL_DATABASE: ${PATIENT_DB_NAME}
      MYSQL_USER: ${PATIENT_DB_USERNAME}
      MYSQL_PASSWORD: ${PATIENT_DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    restart: always
  mysql-appointment-service:
    image: mysql:8.0
    container_name: mysql-appointment-service
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${APPOINTMENT_DB_PASSWORD}
      MYSQL_DATABASE: ${APPOINTMENT_DB_NAME}
      MYSQL_USER: ${APPOINTMENT_DB_USERNAME}
      MYSQL_PASSWORD: ${APPOINTMENT_DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    networks:
      - app-network
    restart: always
  mysql-medical-exam-service:
    image: mysql:8.0
    container_name: mysql-medical-exam-service
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MEDICAL_EXAM_DB_PASSWORD}
      MYSQL_DATABASE: ${MEDICAL_EXAM_DB_NAME}
      MYSQL_USER: ${MEDICAL_EXAM_DB_USERNAME}
      MYSQL_PASSWORD: ${MEDICAL_EXAM_DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    networks:
      - app-network
    restart: always

  # Application Services
  config-server-pro:
    image: dnhphong2005/config-server:latest
    container_name: config-server-pro
    environment:
      - SERVICE=config-server
    env_file:
      - .env
    networks:
      - app-network
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:${CONFIG_SERVER_PORT}/actuator/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
  discovery-service-pro:
    image: dnhphong2005/discovery-service:latest
    container_name: discovery-service-pro
    environment:
      - SERVICE=discovery-service
    env_file:
      - .env
    ports:
      - "${DISCOVERY_SERVICE_PORT}:${DISCOVERY_SERVICE_PORT}"
    depends_on:
      config-server-pro:
        condition: service_healthy
    networks:
      - app-network
    restart: always
  api-gateway-pro:
    image: dnhphong2005/api-gateway:latest
    container_name: api-gateway-pro
    environment:
      - SERVICE=api-gateway
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    depends_on:
      config-server-pro:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - app-network
    restart: always
  auth-service-pro:
    image: dnhphong2005/auth-service:latest
    container_name: auth-service-pro
    environment:
      - SERVICE=auth-service
    depends_on:
      config-server-pro:
        condition: service_healthy
      mysql-auth-service:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - app-network
    restart: always
  medicine-service-pro:
    image: dnhphong2005/medicine-service:latest
    container_name: medicine-service-pro
    environment:
      - SERVICE=medicine-service
    depends_on:
      config-server-pro:
        condition: service_healthy
      mysql-medicine-service:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - app-network
    restart: always
  patient-service-pro:
    image: dnhphong2005/patient-service:latest
    container_name: patient-service-pro
    environment:
      - SERVICE=patient-service
    depends_on:
      config-server-pro:
        condition: service_healthy
      mysql-patient-service:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - app-network
    restart: always
  hr-service-pro:
    image: dnhphong2005/hr-service:latest
    container_name: hr-service-pro
    environment:
      - SERVICE=hr-service
    depends_on:
      config-server-pro:
        condition: service_healthy
      mysql-hr-service:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - app-network
    restart: always
  appointment-service-pro:
    image: dnhphong2005/appointment-service:latest
    container_name: appointment-service-pro
    environment:
      - SERVICE=appointment-service
    ports:
      - "${APPOINTMENT_SERVICE_PORT}:${APPOINTMENT_SERVICE_PORT}"
    depends_on:
      config-server-pro:
        condition: service_healthy
      mysql-appointment-service:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - app-network
    restart: always

  medical-exam-service-pro:
    image: dnhphong2005/medical-exam-service:latest
    container_name: medical-exam-service-pro
    environment:
      - SERVICE=medical-exam-service
    ports:
      - "${MEDICAL_EXAM_SERVICE_PORT}:${MEDICAL_EXAM_SERVICE_PORT}"
    depends_on:
      config-server-pro:
        condition: service_healthy
      mysql-medical-exam-service:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
